# Generated by Django 4.0.3 on 2022-07-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('path', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('code', models.TextField()),
                ('language', models.CharField(default='python', max_length=50)),
            ],
        ),
    ]
