# Generated by Django 4.1.2 on 2022-11-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_board_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="board", name="viewers", field=models.IntegerField(default=0),
        ),
    ]
