# Generated by Django 4.0.3 on 2022-07-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_rename_pub_data_question_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_Text',
            new_name='choice_text',
        ),
    ]
